### ISSUE TITLE
这种用法无法解决dns解析被网络运营商解析成错误的ip地址的问题

### ISSUE THREAD

**Issue by kris520** [qiniu/happy-dns-android#15]
如果resolvers[0]能解析到ip地址，就算这个ip地址是无法访问的，也永远不会使用resolvers[1]

    IResolver[] resolvers = new IResolver[2];
    resolvers[0] = AndroidDnsServer.defaultResolver();
    resolvers[1] = new Resolver(InetAddress.getByName("8.8.8.8"));
    dns = new DnsManager(NetworkInfo.normal, resolvers);

**Comment by HugoLipeng** [comment]
目前已经提供给你修改后的jar包

**Comment by longbai** [comment]
这个只是例子，可以按照自己的方式构造DNSManager
