### ISSUE TITLE
DnsException 出现 ZipException 运行时异常

### ISSUE THREAD

**Issue by liangzhitao** [qiniu/happy-dns-android#3]
编译 OK，无法打包。
```
Error:Execution failed for task ':app:transformClassesWithJarMergingForOfficialDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/qiniu/android/dns/DnsException.class
```

**Comment by longbai** [comment]
哦，被重复打包了，麻烦看下 是否有其他项目 包含了

**Comment by liangzhitao** [comment]
之前是一直没问题，然后升级 Android Studio 2.0 ，更改了几个不相关的文件，就出现这种情况，clean，rebuild，一直不行。目测可能是 AS 2.0 的 bug ，删了 project 的 happy-dns 的依赖，再删了 happy-dns 的 jar 包，gradle resync，extended libraries 里仍然有  happy-dns 库...
